language: cpp
env:
  global: 
    - secure: "YXw3gWbrrN5pxLfwjQdymchep9FvfwB3cFofN+PXk4T9hNomsTkrDUDBrL/mifMSAXq7ITeKg8EaIUiIIGI7pSHP/ZEnyIB7VYO9ggJ2izxlFNGA20NfoJ3Yrch3AnYiQDswsCFlngfqeOgwvuIQMUp/Sn1EcWiEGT+VZhuGY4o="
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
    - os: osx
      osx_image: xcode11
      env: OSX=10.14 CC=gcc CXX=g++ 
      compiler: clang
    - os: osx
      osx_image: xcode11
      env: OSX=10.14 
      compiler: clang
    - os: osx
      osx_image: xcode10
      env: OSX=10.13 
      compiler: clang
    - os: osx
      osx_image: xcode9.2
      env: OSX=10.12 
      compiler: clang

before_script:
  - if [[ "$TRAVIS_OS_NAME $CC" == "osx clang" ]]; then  export PLATFORM=osx$OSX-x86_64-clang`clang -dumpversion`; fi
  - if [[ "$TRAVIS_OS_NAME $CC" == "osx gcc" ]]; then  export PLATFORM=osx$OSX-x86_64-gcc`gcc -dumpversion`; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install bash gcc; clang --version; gfortran --version; fi
  - if [[ "$TRAVIS_OS_NAME $CC" == "osx gcc" ]]; then export CC=gcc-9 ; export CXX=g++-9 ; $CC --version; $CXX --version; fi
  - cd ..
  - wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
  - export PROJECT_URL=https://github.com/$TRAVIS_REPO_SLUG
  - export PROJECT=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
  - bash ./coinbrew fetch $PROJECT_URL:$TRAVIS_BRANCH --no-prompt --skip-update  > /dev/null 

script:
  - bash ./coinbrew build $PROJECT --no-prompt --verbosity=2 --test
after_script:
  - if [ $TRAVIS_BRANCH = "master" ]; then export VERSION=master; else export VERSION=`echo $TRAVIS_BRANCH | cut -d "/" -f 2`; fi
  - export TGZ_FILE=$PROJECT-$VERSION-$PLATFORM.tgz
  - echo $TGZ_FILE
  - cp $PROJECT/README.md $PROJECT/LICENSE $PROJECT/$PROJECT/AUTHORS dist
  - cd dist
  - tar -czvf $TGZ_FILE lib/* bin/* include/* share/* README.md LICENSE AUTHORS
  - curl -T $TGZ_FILE -utkralphs:$BINTRAY_API -H "X-Bintray-Publish:1" -H "X-Bintray-Override:1" https://api.bintray.com/content/coin-or/download/$PROJECT/$VERSION/$TGZ_FILE
